version: '3.9'

services:
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && npx serve -s build"
    ports:
      - "3000:5000"
