name: Run NPM Commands

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: List directory contents
      run: ls

    - name: Change directory to 'demo'
      run: cd demo

    - name: Install dependencies
      run: npm install

    - name: Start the application
      run: npm start
